import { PresetStructure } from "./types";

const audioPresets: PresetStructure = {
  activation: {
    tooLow: [
      {
        id: "activation_tooLow_boostEnergy_01",
        mood: "boostEnergy",
        bpm: [140, 160],
        loudnessDb: [75, 80],
        tempoStyle: "EDM/DnB",
        loopUrls: ["/audio/activation", "/audio/activation"],
        loop: true,
        fadeInMs: 1000,
        fadeOutMs: 1000,
        freqHz: [440, 880],
        brainwaveHz: [14, 18],
        brainwaveType: "beta",
        label: "Boost Energy",
        debugLabel: "Activation-BoostEnergy-HRTooLow",
        description: "Fast-paced EDM/DnB to energize low heart rate states.",
      },
    ],
    optimal: [
      {
        id: "activation_optimal_maintainFocus_01",
        mood: "maintainFocus",
        bpm: [130, 140],
        loudnessDb: [70, 75],
        tempoStyle: "Pop/Rock",
        loopUrls: ["/audio/activation", "/audio/activation"],
        loop: true,
        fadeInMs: 1000,
        fadeOutMs: 1000,
        freqHz: [435, 440],
        brainwaveHz: [40, 40],
        brainwaveType: "gamma",
        label: "Maintain Focus",
        debugLabel: "Activation-MaintainFocus-HROptimal",
        description:
          "Driving pop/rock rhythm to sustain peak performance focus.",
      },
    ],
    tooHigh: [
      {
        id: "activation_tooHigh_controlIntensity_01",
        mood: "controlIntensity",
        bpm: [110, 120],
        loudnessDb: [65, 70],
        tempoStyle: "Groove",
        loopUrls: ["/audio/activation", "/audio/activation"],
        loop: true,
        fadeInMs: 1000,
        fadeOutMs: 1000,
        freqHz: [432, 432],
        brainwaveHz: [14, 14],
        brainwaveType: "beta",
        label: "Control Intensity",
        debugLabel: "Activation-ControlIntensity-HRTooHigh",
        description: "Groove-based audio to regulate high heart rate levels.",
      },
    ],
  },
  sustained: {
    tooLow: [
      {
        id: "sustained_tooLow_encouragePace_01",
        mood: "encouragePace",
        bpm: [120, 130],
        loudnessDb: [70, 75],
        tempoStyle: "House",
        loopUrls: ["/audio/activation", "/audio/activation"],
        loop: true,
        fadeInMs: 1000,
        fadeOutMs: 1000,
        freqHz: [435, 438],
        brainwaveHz: [14, 14],
        brainwaveType: "beta",
        label: "Encourage Pace",
        debugLabel: "Sustained-EncouragePace-HRTooLow",
        description:
          "Uplifting house rhythm to increase running cadence and energy.",
      },
    ],
    optimal: [
      {
        id: "sustained_optimal_supportRhythm_01",
        mood: "supportRhythm",
        bpm: [105, 115],
        loudnessDb: [65, 70],
        tempoStyle: "Lo-fi/Pop",
        loopUrls: ["/audio/activation", "/audio/activation"],
        loop: true,
        fadeInMs: 1000,
        fadeOutMs: 1000,
        freqHz: [432, 435],
        brainwaveHz: [10, 10],
        brainwaveType: "alpha",
        label: "Support Rhythm",
        debugLabel: "Sustained-SupportRhythm-HROptimal",
        description: "Steady lo-fi/pop to maintain smooth pacing and flow.",
      },
    ],
    tooHigh: [
      {
        id: "sustained_tooHigh_calmBreathing_01",
        mood: "calmBreathing",
        bpm: [90, 100],
        loudnessDb: [60, 65],
        tempoStyle: "Jazz/Funk",
        loopUrls: ["/audio/activation", "/audio/activation"],
        loop: true,
        fadeInMs: 1000,
        fadeOutMs: 1000,
        freqHz: [428, 432],
        brainwaveHz: [6, 6],
        brainwaveType: "theta",
        label: "Calm Breathing",
        debugLabel: "Sustained-CalmBreathing-HRTooHigh",
        description: "Mellow jazz/funk to slow breathing and lower intensity.",
      },
    ],
  },
  recovery: {
    tooLow: [
      {
        id: "recovery_tooLow_preventUnderrelaxation_01",
        mood: "preventUnderrelaxation",
        bpm: [70, 80],
        loudnessDb: [60, 65],
        tempoStyle: "Light Ambient",
        loopUrls: ["/audio/activation", "/audio/activation"],
        loop: true,
        fadeInMs: 1000,
        fadeOutMs: 1000,
        freqHz: [432, 432],
        brainwaveHz: [10, 10],
        brainwaveType: "alpha",
        label: "Prevent Under-Relaxation",
        debugLabel: "Recovery-PreventUnderRelaxation-HRTooLow",
        description: "Light ambient textures to keep recovery active but soft.",
      },
    ],
    optimal: [
      {
        id: "recovery_optimal_deepenRelaxation_01",
        mood: "deepenRelaxation",
        bpm: [60, 70],
        loudnessDb: [55, 60],
        tempoStyle: "Drone/Ambient",
        loopUrls: ["/audio/activation", "/audio/activation"],
        loop: true,
        fadeInMs: 1000,
        fadeOutMs: 1000,
        freqHz: [432, 432],
        brainwaveHz: [2, 4],
        brainwaveType: "delta",
        label: "Deepen Relaxation",
        debugLabel: "Recovery-DeepenRelaxation-HROptimal",
        description:
          "Slow ambient drones to encourage parasympathetic recovery.",
      },
    ],
    tooHigh: [
      {
        id: "recovery_tooHigh_forceRecovery_01",
        mood: "forceRecovery",
        bpm: [50, 60],
        loudnessDb: [50, 55],
        tempoStyle: "Breath Cues",
        loopUrls: ["/audio/activation", "/audio/activation"],
        loop: true,
        fadeInMs: 1000,
        fadeOutMs: 1000,
        freqHz: [100, 430],
        brainwaveHz: [1, 2],
        brainwaveType: "delta",
        label: "Force Recovery",
        debugLabel: "Recovery-ForceRecovery-HRTooHigh",
        description: "Breath-guided tones to actively downregulate heart rate.",
      },
    ],
  },
};

export default audioPresets;
